name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Check out repository
      uses: actions/checkout@v3

    # 2. Docker 빌드 및 푸시
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t spinai/spinaisera:latest .
        docker push spinai/spinaisera:latest

    # 3. EC2 서버에 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        debug: true
        script: |
            # GitHub 리포지토리 클론 (이미 클론된 경우를 대비하여 폴더 삭제)
            rm -rf /home/ubuntu/project || true
            git clone https://github.com/yejelim/spinaisera.git /home/ubuntu/project
            cd /home/ubuntu/project
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
            # 기존 컨테이너 및 네트워크 깔끔하게 정리
            docker stop spinaisera || true
            docker rm spinaisera || true

            # 이후 새로운 컨테이너 배포
            docker-compose pull
            docker-compose up -d
